### PR TITLE
feat: better badge

### PR DESCRIPTION
**Pull request by alanshaw**
* Aligns text better within box
* Adds 2x resolution PNG version
* Adds vector version
* Uses vector version on README
* Adds badge markdown code to README

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
The SVG version seems misaligned for me on Firefox: 
image
https://github.com/alanshaw/interface-ipfs-core/blob/b06fd98422f136a1f8cadc0b3487eeb706fe837d/img/badge.svg

**Comment by alanshaw** [comment]
oh no, where are your fonts?

**Comment by alanshaw** [comment]
Maybe it needs a fallback to Helvetica

**Comment by alanshaw** [comment]
Better now @VictorBjelkholm?

**Comment by VictorBjelkholm** [comment]
@alanshaw aren't both Helvetica and Helvetica Neiu osx-only fonts? Unless you have a license of course. Should probably just fallback to `sanf-serif`. Anyways, looks better now :+1: 

image

**Comment by alanshaw** [comment]
It look ok in this window:

screen shot 2018-03-27 at 14 27 19

**Pull request merged**
