### PR TITLE
feat: REPO spec

### PR DESCRIPTION
**Pull request by hacdias**

### CODE REVIEW

**Comment by hacdias** [comment]
@diasdavid just wrote the SPEC for `.repo`. What do you think?
This comes with https://github.com/ipfs/js-ipfs-api/pull/678 which also fixes a bug.

**Comment by hacdias** [comment]
Done @diasdavid

**Comment by diasdavid** [comment]
@hacdias check merge conflicts

**Comment by hacdias** [comment]
@diasdavid rebased into master 😄

**Pull request merged**
