### PR TITLE
Normalize KEY API

### PR DESCRIPTION
**Pull request by hacdias**
- [x] Normalize API with non-capitalized object fields
- [x] Wait for https://github.com/ipfs/js-ipfs-api/pull/659 to be completed.
- [x] Update Tests
 
Ref.: https://github.com/ipfs/js-ipfs-api/pull/659

### CODE REVIEW

**Comment by hacdias** [comment]
@diasdavid just noticed that there is a `ipfs.key.export` in the SPEC but it is not a command on GO-IPS, nor in JS-IPFS, nor in the HTTP API.

Is it some TODO or should be removed?

**Comment by hacdias** [comment]
@diasdavid done. Should be merged alongside with https://github.com/ipfs/interface-ipfs-core/pull/192.

**Comment by hacdias** [comment]
@diasdavid done. Should be merged alongside with https://github.com/ipfs/interface-ipfs-core/pull/192.

**Comment by richardschneider** [comment]
@hacdias PR https://github.com/ipfs/js-ipfs/pull/1133 has the implementation (core, cli and http) for the Key API.  Waiting for approval from @diasdavid 

With the case change, you will also need to change core to use lower case, because core and http-api must be compatible.  

However, http must still return Capitalized names because that is the spec defined by `go-ipfs`.  This allows a go client to use a js-ipfs daemon.

The cli can either talk directly to core or use http-api, so it must be changed to use lower case.

**Comment by hacdias** [comment]
@richardschneider oops! Didn't notice that PR.

I just made this (and ipfs/js-ipfs-api#659) because most of the JS API is using non-capitalized object fields and that's just like the Standard specification tells us.

As far as I understood:

- HTTP API must return capitalized names (so `js-ipfs` and `go-ipfs` must return them that way).
- External APIs should be compliant to each language standard, which, in JS case, is to be non-capitalized.

Did I miss something?

**Comment by richardschneider** [comment]
@hacdias I think we are on the same page.  When these `normalize`  PRs are released, please ping me and I'll update https://github.com/ipfs/js-ipfs/pull/1133

**Comment by hacdias** [comment]
@diasdavid do you agree with what I [said](https://github.com/ipfs/interface-ipfs-core/pull/192#issuecomment-355126953)?

**Comment by diasdavid** [comment]
thank you both for figuring this out and reaching consensus. LGTM :)

**Comment by hacdias** [comment]
Thanks @diasdavid! Pinging @richardschneider 😄

**Pull request merged**
