### PR TITLE
Add bootstrap API spec

### PR DESCRIPTION
**Pull request by richardschneider**
Document the spec as implemented by `js-ipfs`. See #97

### CODE REVIEW

**Comment by richardschneider** [comment]
@diasdavid When the spec is merged, I'll start writing the tests!

**Comment by diasdavid** [comment]
@richardschneider you can use the tests from https://github.com/ipfs/js-ipfs-api/blob/master/test/bootstrap.spec.js just by importing them here.

It would be good to merge the spec with the tests and ensure that both js-ipfs and js-ipfs-api follow it so that we don't confuse users.

**Comment by richardschneider** [comment]
Sounds like a good plan.  Will do tomorrow.

**Comment by richardschneider** [comment]
@diasdavid As requested, I've added the tests.

**Pull request merged**
