### PR TITLE
[WIP] putStream & getStream

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by diasdavid** [comment]
Specwise LGTM, do you want to add the tests as well? :)

**Comment by dignifiedquire** [comment]
> Specwise LGTM, do you want to add the tests as well? :)

was waiting for the thumbs up before doing that, will write them now

**Comment by dignifiedquire** [comment]
done

**Comment by diasdavid** [comment]
For merge:

- [ ] rebase master onto this branch
- [ ] impl in js-ipfs-api
- [ ] impl in js-ipfs

**Comment by dignifiedquire** [comment]
@diasdavid lets make a general plan for how to handle the stream things in here, before we merge this.

**Comment by diasdavid** [comment]
@dignifiedquire closing this PR for now, I believe it won't happen anymore. Correct me if I'm wrong.

**Pull request closed without merging**
