### PR TITLE
provide a clear, linkable path for finding the core API docs

### PR DESCRIPTION
**Pull request by flyingzumwalt**
The README _did_ contain a listing of the core APIs and their functions but it was in a spot that you couldn't link directly to. This PR moves the listing to a spot that we can link to and adds a README at the root of the /API directory that tells people where they've landed and where to find the list of APIs and methods.

refs ipfs/docs#13

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
@diasdavid are you ok with this move?
cc @lgierth

**Comment by lgierth** [comment]
(LGTM)

**Comment by diasdavid** [comment]
> The README did contain a listing of the core APIs and their functions but it was in a spot that you couldn't link directly to.

I added it during this sprint :)

**Comment by diasdavid** [comment]
Thank you @flyingzumwalt :)

**Pull request merged**
