### PR TITLE
chore: increase ping timeouts

### PR DESCRIPTION
**Pull request by alanshaw**
This takes around 15s locally and can take significantly longer in CI.

screenshot 2018-11-27 at 13 37 41

### CODE REVIEW

**Comment by hugomrdias** [comment]
shouldn't we try to improve the code instead of just increasing the mocha timeout ? This shouldn't take this long right 2 * 60 * 1000?

**Comment by alanshaw** [comment]
The screenshot above is from js-ipfs-api talking to a go-ipfs node. Most of the time it takes ~15s but occasionally it takes >1min in CI. I'll open an issue on the go-ipfs repo.

**Comment by alanshaw** [comment]
https://github.com/ipfs/go-ipfs/issues/5799

**Comment by alanshaw** [comment]
@hugomrdias I've added comments with link to the issue. I'm going to merge this so that our ping tests become more reliable and we can revisit when the issue is resolved.

**Pull request merged**
